server:
  port: 8080

spring:
  application:
    name: edgeserver
  cloud:
    discovery:
      client:
        locator:
          enabled: true
          lower-case-service-id: true
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka

        
    
